(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MTDoc=api;})(typeof self!=='undefined'?self:this,function(){'use strict';
const CATEGORIES=['סופרמרקט','מסעדות ובתי קפה','סיגריות ומוצרי טבק','דיור','רכב','דלק','תחבורה','בילויים','קניות','חשבונות','סלולר ואינטרנט','בריאות','ביטוחים','חופשות','ילדים','מנויים','עמלות וריביות','אגרות ושירותים','העברות ותשלומים','הלוואות והחזרים','אחר'];
const TYPES={credit_card:'כרטיס אשראי',bank:'דף חשבון / עו״ש',receipt:'קבלה / חשבונית',salary:'תלוש / הכנסה',loan:'הלוואה / החזר',web:'צילום אתר / מסמך לא פיננסי',other:'אחר'};
function norm(v){return String(v||'').toLowerCase().replace(/[״"'׳']/g,'').replace(/[–—]/g,'-').replace(/\s+/g,' ').trim()}
function classify(v){const s=norm(v),rules=[['סיגריות ומוצרי טבק',/(?:^|\s)(?:פוינט|point)(?:\s|$)|טבק|סיגר|tobacco|cigarette|smoke/],['בריאות',/כללית|מכבי|מאוחדת|לאומית|סופר\s*פארם|פארם|pharm|רופא|בריאות|תרופה|super.?pharm/],['סופרמרקט',/שופרסל|רמי\s*לוי|carrefour|קרפור|ויקטורי|יוחננוף|מגה|סטופמרקט|מינימרקט|סופר(?!\s*פארם)|am\s*:?pm|טיב\s*טעם|market|דוכני?\s*שפע|קצבים/],['מסעדות ובתי קפה',/wolt|וולט|קפה|מסעד|restaurant|coffee|bakery|בייקרי|רולדין|פטיסרי|ארומה|greg|קפה\s*קפה|mcdonald|מקדונלד|מנזה|שומשום/],['תחבורה',/gett|מונית|taxi|רכבת|אגד|רב.?קו|moovit|תחבורה/],['דלק',/פז|yellow|סונול|דור\s*אלון|דלק|fuel|ten\s/],['ביטוחים',/מנורה|מבטחים|הראל|הפניקס|כלל\s*ביטוח|ביטוח|insurance/],['סלולר ואינטרנט',/פרטנר|partner|סלקום|cellcom|פלאפון|hot\s*mobile|תקשורת|internet/],['עמלות וריביות',/דמי\s*כרטיס|עמלה|ריבית|הנפקה|commission|interest/],['אגרות ושירותים',/שגרירות|קונסול|אגרה|משרד\s*הפנים|רשות|gov/],['העברות ותשלומים',/(?:^|\s)bit(?:\s|$)|paybox|העברה|transfer/],['קניות',/zara|nike|adidas|h&m|חנות|shop|terminal\s*x|fox|castro|קסטרו/],['חשבונות',/חשמל|מים|ארנונה|electric|water|מי\s*עיר|עיריית/],['מנויים',/netflix|spotify|apple|google|מנוי|subscription/],['דיור',/שכר\s*דירה|משכנתא|ועד\s*בית|rent|mortgage/],['רכב',/מוסך|חניה|parking|כביש\s*6|איתוראן|רכב/],['חופשות',/hotel|booking|airbnb|מלון|טיסה|el\s*al|אל\s*על/],['ילדים',/גן\s|צהרון|בית\s*ספר|school|ילדים/],['הלוואות והחזרים',/הלוואה|loan|החזר\s*הלווא/]];for(const [c,r] of rules)if(r.test(s))return c;return 'אחר'}
function txKind(v){const s=norm(v);if(/משיכת\s*מזומנים|משיכה\s*מכספומט|atm/.test(s))return'transfer';if(/זיכוי|החזר\s*כספי|ביטול\s*עסקה|refund|credit/.test(s))return'refund';return'expense'}
function detectType(text,ratio=1){const s=norm(text);if(/תלוש|משכורת|שכר\s*ברוטו|שכר\s*נטו/.test(s))return'salary';if(/הלוואה|יתרת\s*הלווא|קרן.*ריבית/.test(s))return'loan';if(/אמריקן|אמקס|american\s*express|ישראכרט|max(?:\s|$)|מקס(?:\s|$)|כאל|cal\s|כרטיס|עסקאות\s*בחיוב|סה.?כ\s*לחיוב/.test(s))return'credit_card';if(/עוש|עו.?ש|חשבון\s*הבנק|יתרה\s*בחשבון|תנועות\s*בחשבון/.test(s))return'bank';if(/קבלה|חשבונית|סה.?כ\s*לתשלום|מע.?מ/.test(s))return'receipt';if(ratio>6&&!/עסקה|חיוב|סכום|חשבון|קבלה|חשבונית/.test(s))return'web';return'other'}
function detectSource(text){const s=String(text||'');let brand='';if(/אמריקן\s*אקספרס|american\s*express|אמקס/i.test(s))brand='American Express';else if(/ישראכרט/i.test(s))brand='ישראכרט';else if(/(?:^|\s)max(?:\s|$)|מקס/i.test(s))brand='MAX';else if(/כאל|cal/i.test(s))brand='כאל';else if(/visa|ויזה/i.test(s))brand='Visa';else if(/mastercard|מאסטר/i.test(s))brand='Mastercard';let last4='';const patterns=[/(?:מסתיים|סיומת|כרטיס|card|\*{2,}|•{2,}|x{2,})[^\n\d]{0,12}(\d{4})(?!\d)/ig,/(?:זהב|ירוק|קלאסיק|gold|green|classic)[^\n\d]{0,18}(\d{4})(?!\d)/ig];for(const r of patterns){let m;while((m=r.exec(s)))last4=m[1]}return [brand,last4].filter(Boolean).join(' • ')||'לא זוהה'}
function parseDate(v,reference=new Date()){const s=String(v||'');let m=s.match(/(?:^|\D)(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4})(?:\D|$)/);if(m){let y=+m[3];if(y<100)y+=2000;const mo=+m[2],d=+m[1];if(y>=2000&&y<=2100&&mo>=1&&mo<=12&&d>=1&&d<=31)return`${y}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`}m=s.match(/(?:^|\D)(\d{1,2})[.\/-](\d{1,2})(?:\D|$)/);if(!m)return'';const d=+m[1],mo=+m[2];if(mo<1||mo>12||d<1||d>31)return'';const ref=reference instanceof Date?reference:new Date(reference);let y=ref.getFullYear();if(mo>ref.getMonth()+3)y--;return`${y}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function moneyValues(v){let s=String(v||'');const shek=[...s.matchAll(/₪\s*(-?\d{1,6}(?:,\d{3})*(?:[.,]\d{2})?)/g)].map(m=>Number(m[1].replace(/,/g,''))).filter(Number.isFinite);if(shek.length)return shek.map(Math.abs);s=s.replace(/\b\d{1,2}[.\/-]\d{1,2}[.\/-]\d{2,4}\b/g,' ').replace(/הנחה\s*(?:של)?\s*[\d,.]+/gi,' ');const out=[];for(const m of s.matchAll(/(?:^|\s)(-?\d{1,6}(?:,\d{3})*(?:[.,]\d{2}))(?!\d)/g)){const n=Number(m[1].replace(/,/g,''));if(Number.isFinite(n)&&Math.abs(n)>0.009)out.push(Math.abs(n))}return out}
function statementTotal(text){const raw=String(text||''),patterns=[/סה.?כ\s*(?:לתשלום|לחיוב)[^\n]{0,45}?₪?\s*([\d,]+(?:\.\d{1,2})?)/i,/סה.?כ\s*חיוב[^\n]{0,45}?₪?\s*([\d,]+(?:\.\d{1,2})?)/i,/total[^\n]{0,45}?₪\s*([\d,]+(?:\.\d{1,2})?)/i];for(const r of patterns){const m=raw.match(r);if(m){const n=Number(m[1].replace(/,/g,''));if(n>0)return Math.round(n*100)}}return 0}
function cleanMerchant(v){return String(v||'').replace(/\b\d{1,2}[.\/-]\d{1,2}[.\/-]\d{2,4}\b/g,' ').replace(/₪\s*[\d,.]+/g,' ').replace(/\b\d{1,6}[.,]\d{2}\b/g,' ').replace(/הנחה\s*(?:של)?\s*₪?\s*[\d,.]*/gi,' ').replace(/תשלום\s*\d+\s*מתוך\s*\d+/g,' ').replace(/הוראת\s*קבע|פריסה\s*לתשלומים|תשלום\s*אחרון|עסקה\s*רגילה/gi,' ').replace(/\s+/g,' ').replace(/^[-|:.,\s]+|[-|:.,\s]+$/g,'').trim()}
const IGNORE=/סה.?כ|לחיוב|לתשלום|מסגרת|יתרה|הטבות|סטטוס|פעולות|תאריך\s*עסקה|שם\s*בית\s*עסק|סכום\s*עסקה|פירוט\s*עסקאות|חיובים\s*וזיכויים|דף\s*הבית/;
function makeRow(merchant,date,amount){const type=txKind(merchant);return{merchant,date,amountMinor:Math.round(Math.abs(amount)*100),category:classify(merchant),type,selected:type!=='transfer'}}
function parseLines(lines,referenceDate=new Date()){const clean=lines.map(x=>String(x||'').replace(/\s+/g,' ').trim()).filter(Boolean),rows=[];for(let i=0;i<clean.length;i++){const line=clean[i];if(IGNORE.test(norm(line)))continue;const date=parseDate(line,referenceDate),vals=moneyValues(line);if(date&&vals.length){const merchant=cleanMerchant(line);if(merchant.length>1&&!IGNORE.test(norm(merchant)))rows.push(makeRow(merchant,date,vals[0]));continue}if(date&&!vals.length){let parts=[line],amount=0;for(let j=i+1;j<=Math.min(i+2,clean.length-1);j++){if(parseDate(clean[j],referenceDate))break;parts.push(clean[j]);const v=moneyValues(clean[j]);if(v.length){amount=v[0];break}}if(amount){const merchant=cleanMerchant(parts.join(' '));if(merchant.length>1&&!IGNORE.test(norm(merchant)))rows.push(makeRow(merchant,date,amount))}}if(!date&&vals.length){for(let j=Math.max(0,i-2);j<i;j++){const d=parseDate(clean[j],referenceDate);if(d){const merchant=cleanMerchant(clean.slice(j,i+1).join(' '));if(merchant.length>1&&!IGNORE.test(norm(merchant)))rows.push(makeRow(merchant,d,vals[0]));break}}}}const seen=new Set;return rows.filter(r=>{const k=[r.date,r.amountMinor,norm(r.merchant).slice(0,28)].join('|');if(seen.has(k))return false;seen.add(k);return true})}
function parseTSV(tsv,referenceDate=new Date()){const groups={};String(tsv||'').split(/\r?\n/).slice(1).forEach(row=>{const c=row.split('\t');if(c.length<12||!c[11]||!c[11].trim())return;const key=[c[1],c[2],c[3],c[4]].join('-');(groups[key]||(groups[key]=[])).push({x:+c[6],text:c[11]})});const lines=Object.values(groups).map(a=>a.sort((x,y)=>x.x-y.x).map(x=>x.text).join(' '));return{lines,rows:parseLines(lines,referenceDate)}}
function period(rows){const ds=rows.map(x=>x.date).filter(Boolean).sort();return!ds.length?'לא זוהתה':ds[0]===ds[ds.length-1]?ds[0]:`${ds[0]} עד ${ds[ds.length-1]}`}
function fingerprint(r,source=''){return[norm(source),r.date||'',Math.abs(r.amountMinor||0),norm(r.merchant).replace(/[^a-z0-9א-ת ]/g,'').slice(0,32)].join('|')}
function summarize(rows){const selected=rows.filter(r=>r.selected),byCategory={};let totalMinor=0;for(const r of selected){if(r.type==='transfer')continue;const sign=r.type==='refund'?-1:1;totalMinor+=sign*r.amountMinor;byCategory[r.category]=(byCategory[r.category]||0)+sign*r.amountMinor}return{totalMinor,byCategory:Object.fromEntries(Object.entries(byCategory).filter(([,v])=>v!==0).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]))),count:selected.length}}
return{CATEGORIES,TYPES,norm,classify,txKind,detectType,detectSource,parseDate,moneyValues,statementTotal,cleanMerchant,parseLines,parseTSV,period,fingerprint,summarize};
});